#!/bin/bash

set -e

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
  armv6l) ;&
  armv7l) MACHTYPE=arm ;;
  *) ;;
esac

export MUSL_INCLUDE="${MUSL_INCLUDE-/usr/local/lib}"
export TOTP_LDFLAGS="-I$MUSL_INCLUDE/kernel-headers/generic/include -I$MUSL_INCLUDE/kernel-headers/${MACHTYPE}/include"
export TOTP_CFLAGS="-g -Wall -fwrapv -pedantic"
export LDFLAGS="-I. ${TOTP_LDFLAGS}"
export CC="musl-gcc -static -Os"
exec make $@
